version: '3'
services:
  web:
    build: ./web
    container_name: web
    volumes:
     - ./persist:/persist:Z
    ports:
     - "3000:80"
    depends_on:
     - db
     - db-fixture
    restart: always
  db:
    image: mongo
    container_name: db
    volumes:
     - ./persist/data:/data:Z
    ports:
     - "27017:27017"
    restart: always
  db-fixture:
    build: ./db-fixture
    container_name: db-fixture
    links:
      - db
    depends_on:
      - db
